### ISSUE TITLE
Return code in case bot ends without success

### ISSUE THREAD

**Issue by stheine** [thenativeweb/roboter#18]
When I start 'bot', and one of the messages is:

[12:06:28] Error in plugin 'gitcheckpending'
Message:
    You have pending changes.

I would expect the bot command to return with a non-0 exit code to indicate issues.

**Comment by goloroden** [comment]
Thanks for bringing this up!

We have created an internal issue for this and will update this one as soon as we have any news (or a fix ;-)).

**Comment by goloroden** [comment]
Hi @stheine!

Good news: We have fixed this issue. The fix is included in the new version `0.11.13`.

Thanks again for pointing this out :-)
