### ISSUE TITLE
how to get usage?

### ISSUE THREAD

**Issue by stheine** [thenativeweb/roboter#19]
the documentation says:

If you want to get an overview of all available tasks, simply run bot without any parameters.
$ bot

but in fact, if I simply call 'bot', it executes the configured tasks.

but it's also not answering on 'bot --help'.

please add function to get the usage, and update the documentation.

**Comment by goloroden** [comment]
You're perfectly right here - the documentation is outdated (actually, we had this behavior in a very early version, but then got rid off it in favor of a default task).

We will fix this by introducing a new CLI flag, `--help`, and update this issue once it has been done.

**Comment by goloroden** [comment]
Fixed in `roboter-cli` in new version `0.1.1` :-)

**Comment by stefanheine** [comment]
'release' is missing in the list of commands shown in 'bot --help'.

and I would like to be able to call 'bot release --help' to also see the options of the 'release' command.

**Comment by goloroden** [comment]
`release` is missing because this is only an alias for `publish`.

Regarding the help for `bot release`, we will restructure roboter anyway to highly improve install times, and after that we can discuss this behavior ;-)

If it's important for you, please open a new issue for this, or send a PR ;-)
