### ISSUE TITLE
Exiting long running commands like analyse or build does not end child processes.

### ISSUE THREAD

**Issue by mattwagl** [thenativeweb/roboter#286]
### What is this bug about?

When executing long running tasks that use shelljs to spawn child processes like for example `build`, we currently do not exit these child processes when the main roboter process is exited by the user.

### What is the expected result?

All child processes should be stopped as well when the user exits a command.

### What is the actual result?

roboter does not end child processes when exiting the current task with `Ctrl-C`.

### What steps are needed to reproduce the bug?

- Start a long running `build` or `analyse` process 
- Hit Ctrl-C
- Monitor the currently running Node processes (e.g. using the ActivityMonitor on macOS) to see the child process being still active 

### What else should we know?

In most of the use cases this is not a problem. However if the TypeScript compilation or the eslint analysis gets stuck, it is possible produce hanging processes. 

[The `runCommand` module](https://github.com/thenativeweb/roboter/blob/ed36fc9aea07116babc9edf9238f8e60802effb0/lib/runCommand.js#L21-L39) is responsible for executing commands. We already have [a blueprint for cleaning up child processes](https://github.com/thenativeweb/runfork/blob/5b52d08146049acb4d27f272fe2f2c6a091cdeea/lib/runfork.ts#L29-L35) in the `run-fork` module. It looks like we should be able to apply the same kind of behaviour inside `runCommand`.

**Comment by goloroden** [comment]
This is done in roboter@12
