### ISSUE TITLE
<!-- toc --> not properly working. how to troubleshoot?

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#29]
I have seen cases where the  section in the README.md is not properly updated. how can I troubleshoot this? I would have expected an option to run this as a separate step, like 'bot toc'.

**Comment by goloroden** [comment]
Thanks for bringing up this issue :-)

Can you elaborate on what these cases are?

What would be of special interest is:

- Is the behavior reproducible?
- What does "is not properly updated" mean?

**Comment by stefanheine** [comment]
the toc section in my README.md has been generated by a previous bot publish and looks like:

> 
> 
> - [Purpose](#purpose)
> - [References](#references)
> - [Installation](#installation)
>   - [Demo Environment setup](#demo-environment-setup)
>   - [Logging](#logging)
> - [API-Usage](#api-usage)
> - [API](#api)
>   - [Server, shared space, workspace](#server-shared-space-workspace)
>   - [Query parameter](#query-parameter)
>   - [createEntity({entityType, data})](#createentityentitytype-data)
>   - [deleteEntity({entityType, id})](#deleteentityentitytype-id)
>   - [readEntity({entityType, id}) or readEntity({entityType, qs})](#readentityentitytype-id-or-readentityentitytype-qs)
>   - [updateEntity({entityType, id, updateFields})](#updateentityentitytype-id-updatefields)
> - [TODO](#todo)
> 
> 

on the latest bot publish it didn't get updated, even though the README.md has changed a lot (changed and added sections with headlines).

I don't want to reproduce this, as currently the only way to do this would be to run another bot publish, increasing my version number - that's why I wonder how I could troubleshoot this without having to run bot publish.

**Comment by goloroden** [comment]
To re-run generation of the TOC, use the `generate-toc` task.

**Comment by stefanheine** [comment]
thanks. I had checked the documentation for such a feature, but there isn't anything (not online, nor in bot --help).

now I found that the toc is not updated if marked as:

> 
> [...]
> 

but it is for:

> 

so where does the bad syntax come from? I guess from a collegues editor integrated tool to generate the toc... I'll check locally.

**Comment by goloroden** [comment]
Sounds reasonable.

I'm going to close this issue assuming that this actually was a problem with one of your colleagues' editor. If it was not, feel free to reopen.
