### ISSUE TITLE
documentation missing the option 'generate-toc'

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#30]
please add the option 'generate-toc' to the bot help and maybe even to the online doc.

**Comment by goloroden** [comment]
Would mind sending a PR?

**Comment by stefanheine** [comment]
eigentlich schon. ich bin sicher, du weisst, wo im code du die help generierst und fixst das in minuten.

**Comment by goloroden** [comment]
You need to update `roboter-cli` to `0.3.1` to get the new help text.

```bash
$ npm install -g roboter-cli
```

**Comment by stefanheine** [comment]
thanks
