### ISSUE TITLE
roboter install hangs

### ISSUE THREAD

**Issue by holger-rode** [thenativeweb/roboter#31]
npm install roboter hangs, because it requires lodash@4.16.6 and npm somehow reports that this is an invalid version:
$ npm install lodash@4.16.6
projects/my-module
└── lodash@4.16.6  invalid
npm verb exit [ 0, true ]
npm info ok

**Comment by goloroden** [comment]
```bash
$ npm install lodash@4.16.6
```

works perfectly for me, and [according to GitHub](https://github.com/lodash/lodash/tree/4.16.6),  there also was a version with that number.

Also

```bash
$ npm show lodash@* version
```

definitely reports that version `4.16.6` exists and is on npm.

What *exactly* is the problem that you have with installing roboter? What are the steps to reproduce the issue?

**Comment by holger-rode** [comment]
Same steps as yesterday simply work fine today, so I call it an intermittent issue with npm :)

**Comment by goloroden** [comment]
😊
