### ISSUE TITLE
bot watch-server

### ISSUE THREAD

**Issue by joachimhb** [thenativeweb/roboter#32]
while until version 0.13.8 the unit-tests were executed after each file change, in 0.13.9 and 0.13.10 the unit-tests are only executed once. 
at least on my windows machine.

**Comment by goloroden** [comment]
I'm very sorry, but I can't reproduce this issue.

Can you please come up with more details?

**Comment by joachimhb** [comment]
Sorry it took so long...
Well, i was able to reproduce it 3 times, but now I'm unable to... really weird... so I guess this issue can be closed until i can reproduce it.

Thanks for checking anyway.

**Comment by joachimhb** [comment]
I just found out how to reproduce it:
It needs one failed unit test, so since using gulp-sequence instead of run-sequence the tests are only executed after a change until one unit test fails.

**Comment by goloroden** [comment]
We are currently rewriting roboter from scratch, so this shouldn't be an issue any more once the new version has been published.
