### ISSUE TITLE
watch-app should support https

### ISSUE THREAD

**Issue by stheine** [thenativeweb/roboter#36]
today, `roboter watch-app` only starts an `http` hosted webpack server.

due to the authentication built into our applications, the application must run with `https`, due to the need to secure cookies.

can you please enhance roboter to allow an optional setting of `https` set in `roboter.js`, and pass this into `roboter/lib/tasks/client/watch-app/index.js` to set into the `new WebpackDevServer(` configuration?

see: https://webpack.js.org/configuration/dev-server/#devserver-https

**Comment by goloroden** [comment]
Released as part of `roboter@0.14.5`.
