### ISSUE TITLE
build-app fails with jsx

### ISSUE THREAD

**Issue by mathiskeller** [thenativeweb/roboter#38]
Not able to build an react app. Always getting following error during build process.

```
Module parse failed: .../src/index.jsx Unexpected token (12:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (12:2)
```

Line 12 of index.jsx looks like `<div className='screen-wrapper'>`

roboter.js build task:
```
    task('client/build-app', {
      entryFiles: [
        './index.html',
        './index.scss',
        './index.jsx'
      ],
      babelize: [ '.src/' ],
      buildDir: 'build/',
      publicPath: '/'
    });
```
Using a .babelrc file with following configuration: 
```
{
  "presets": [ "es2015", "react" ]
}
```

**Comment by goloroden** [comment]
Which version of roboter are you using?

**Comment by mathiskeller** [comment]
I'm using 0.14.5

**Comment by goloroden** [comment]
Did it work before (e.g., using an older version of roboter), or are you experiencing this issue for the first time (i.e., it is a new project)?

**Comment by goloroden** [comment]
PS: In your `roboter.js` file, are you sure that the line

```javascript
babelize: [ '.src/' ]
```

is correct? The path `.src/` looks a little bit strange, IMHO.

**Comment by mathiskeller** [comment]
It's a new project. Only used a very early version of roboter before in an other project.

Just tested. The default:
```
babelize: [ 'src/' ]
```
didn't worked, too.


As soon as i removed the babelize option `bot build-client` worked:

```
    task('client/build-app', {
      entryFiles: [
        './index.html',
        './index.scss',
        './index.jsx'
      ],
      buildDir: 'build/',
      publicPath: '/'
    });
```

**Comment by goloroden** [comment]
Can you please try

```javascript
babelize: [ path.join(__dirname, 'src') ]
```

?

**Comment by mathiskeller** [comment]
Solved my problem 👍

**Comment by goloroden** [comment]
Great 😊

Note to ourselves: We have to update `README.md` to reflect the changes.

BTW: Greetings from @mattwagl 😊

**Comment by mathiskeller** [comment]
Thank you for the fast help 😊 

Greetings back to @mattwagl. ☺️

**Comment by goloroden** [comment]
I would like to leave this open as a reminder to us that we need to update the `README.md` file, hence reopened.

**Comment by goloroden** [comment]
Fixed.
