### ISSUE TITLE
Default action for the client should be build-client, not watch-client

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/roboter#39]
Currently, when running in a client environment, `bot` runs the `watch-client` task. This is inconsistent with the server environment, where this runs code analysis, tests, license checks, …

We should change this.

(This was originally requested by @stefanheine)

**Comment by stefanheine** [comment]
Any feedback on this?

I'm asking, since even the workaround you had mentioned at that time (bot build) does not execute all the needed tasks.

Instead, my workaround is:

bot analyze test-units test-integration unused-dependencies outdated

**Comment by goloroden** [comment]
Right now, unfortunately no.

We are still waiting for Gulp 4 and try not to do big changes until then.

**Comment by goloroden** [comment]
We are currently rewriting roboter from scratch, so this shouldn't be an issue any more once the new version has been published.
