### ISSUE TITLE
eslint-plugin problem with node 8/ npm 5

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#43]
There is a problem with eslint-plugins when using roboter with node 8/ npm 5.

To reproduce, download the attached file.

The first is to show how it works correctly using node 6/ npm 3.10.10:
```
tar xvf eslinttest.tar
cd eslinttest
nvm use 6.10.3  # with npm 3.10.10
npm install
eslint test.js
# -> 3:7  error  Unexpected exclusive mocha test  mocha/no-exclusive-tests
```

now try the same with node 8/ npm 5:
```
rm -rf node_modules
nvm use 8.1.3 # with npm 5.2.0
npm install
eslint test.js
# no errors
```
so why is that?

it can be fixed by installing the `eslint-plugin-mocha` on the top level (even though the identical version is already installed as part of roboter).
```
npm install --save-dev eslint-plugin-mocha@4.9.0
eslint test.js
# ->  3:7  error  Unexpected exclusive mocha test  mocha/no-exclusive-tests
```

so that indicates to me that eslint is unable to find it's plugin if they are installed as part of roboter only.

I'm still submitting this to roboter, as this is the tool we're using to install the linting environment, and it should bring what's needed, or document what needs to be installed to make it run correctly.

**Comment by stefanheine** [comment]
the attached zip file contains the tar file mentioned in the issue above.
[eslinttest.zip](https://github.com/thenativeweb/roboter/files/1141766/eslinttest.zip)

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊 

Just to clarify things a little bit: What happens if you delete the `node_modules` folder entirely, delete the `package-lock.json` file, run `npm install` from scratch, and then run `bot`? Do you still get the same result?

**Comment by stefanheine** [comment]
yes - every time I toggle between node 6 and 8, I clean these files.

**Comment by goloroden** [comment]
Hm, okay… we will need to look into this.

**Comment by goloroden** [comment]
We are currently rewriting roboter from scratch, so this shouldn't be an issue any more once the new version has been published.
