### ISSUE TITLE
Error with command `analyse` on Windows Machines

### ISSUE THREAD

**Issue by davelosert** [thenativeweb/roboter#445]
When running `npx roboter analyse` on a windows machine, we got the following error:

```
Running code analysis...
Oops! Something went wrong! :(
ESLint: 7.13.0
No files matching the pattern "'release.config.js'" were found.
Please check for typing mistakes in the pattern.
✗ Malformed code found.
─────────────────────────────────────────────────────────────────────────────────────────────────────── Code malformed.
AnalysisFailed: Code malformed.
at analyseTask (C:\dev\demo-project\node_modules\roboter\lib\cli\tasks\analyse.js:25:15)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.run (C:\dev\demo-project\node_modules\roboter\lib\cli\commands\qa.js:38:5)
at async C:\dev\demo-project\node_modules\roboter\lib\bin\roboter.js:113:5
```

The `relase.config.js` File exists. It seems like the Glob-Pattern is not matching.
The error message also shows additional quotes around the file-name which might be the cause of error.

**Comment by goloroden** [comment]
@davelosert `roboter` is not supported on Windows so far – which just means that we don't test it. It may work, or it may not work. Apparently it does not. Can you please elaborate a little bit on this and submit a PR?

**Comment by goloroden** [comment]
This is done in roboter@12
