### ISSUE TITLE
please upgrade eslint-plugin-mocha to 4.11.0

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#45]
Hi, can you please upgrade the dependency on eslint-plugin-mocha to 4.11.0 for https://github.com/lo1tuma/eslint-plugin-mocha/commit/9fc05c4bc0e848ec7c5b473624eb6c894c464306

Regards
  Stefan

**Comment by goloroden** [comment]
Would you mind creating a PR?

**Comment by stefanheine** [comment]
I thought about it, but I decided not to do this.

if it's just the one-line fix to update package.json, it's as easy for you as it is for me.

but seeing that you always release roboter together with roboter-server and roboter-client, there seems to be some more magic involved...

**Comment by stefanheine** [comment]
workaround, until the roboter fix is out:

manually install eslint-plugin-mocha@4.11.0 in your project. then the newer version is used by mocha.

**Comment by mattwagl** [comment]
@stefanheine Thanks for sending the PR! The black magic of the double release is actually done by [`publish.js`](https://github.com/thenativeweb/roboter/blob/master/publish.js), so your fix should be fine. I think @goloroden can take care of publishing once he's back from his latest travel adventures. Thanks for you patience!

**Comment by goloroden** [comment]
I have just merged the PRs (thanks a lot for submitting them! 🎉), and I am now going to release a new version.
