### ISSUE TITLE
latest git version on windows can't perform certain release steps anymore

### ISSUE THREAD

**Issue by franzjosefwirtz** [thenativeweb/roboter#49]
When using `bot release`  this command fails to:

- add the new release tag to github
- push package.json with new release number to github.

This happens on windows with latest `git version 2.16.1.windows.2` (taken from https://git-scm.com/download/win) and roboter 0.15.6

In the processing output there is a fatal error:

```
Starting '_release-commit'...
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```

When downgrading to `git version 2.11.1.windows.1` it works, though it already gives a warning:

```
Starting '_release-commit'...
[master 6f53d1b] Release 0.1.6.
1 file changed, 1 insertion(+), 1 deletion(-)
warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
```

**Comment by goloroden** [comment]
Hi Franz-Josef!

Thanks for reporting this issue 😊

As we are currently rewriting roboter from scratch, I don’t think that we are going to fix this. Of course, If you can send a PR, we can merge it!
