### ISSUE TITLE
bot release in a forked repo with different default branch name

### ISSUE THREAD

**Issue by StefanScherer** [thenativeweb/roboter#51]
Hi,

I run into a problem with `bot release` in a forked repo. We have forked a public repo, added roboter to maintain our own releases at NPM in our namespace to be independent from the upstream maintainer release cycles. For forked repos we prefer to keep `master` the 1:1 copy of upstream/master to be able to send pull requests upstream. Therefore our default branch is different from master, we also changed GitHub's default branch. So a git clone normally clones our maintained branch, in our case the default branch name is `sealsystems`.

Now `bot release` has some road blocks for us as these tasks use the fixed `master` branch name.

* `gitnobehind`

```
[16:54:13] Starting '_gitnobehind'...
fatal: ambiguous argument 'master...origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[16:54:15] '_gitnobehind' errored after 1.62 s
[16:54:15] Error in plugin 'gitnobehind'
```

* `release-push`

```
[17:05:44] '_release-push' errored after 10 ms
[17:05:44] Error: Command failed: git push origin master --tags
error: src refspec master does not match any.
error: failed to push some refs to 'git@github.com:sealsystems/node-ipp'
```

I manually patched these two files to push a release to NPM:

* https://github.com/thenativeweb/roboter/blob/1e7c0e3d2565febe8eefe7c9b2deef3e90b2a8ab/lib/tasks/universal/gitnobehind/index.js#L9
* https://github.com/thenativeweb/roboter/blob/1e7c0e3d2565febe8eefe7c9b2deef3e90b2a8ab/lib/tasks/universal/release/index.js#L70

Any idea how we can make this branch name customizable?

Some more details about my cloned repo:

```
$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:sealsystems/node-ipp
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "sealsystems"]
	remote = origin
	merge = refs/heads/sealsystems
[branch "eslint"]
	remote = origin
	merge = refs/heads/eslint
```

```
$ git branch -a
  eslint
* sealsystems
  remotes/origin/HEAD -> origin/sealsystems
  remotes/origin/eslint
  remotes/origin/master
  remotes/origin/sealsystems
  remotes/origin/streamingclient
```

A  `git branch` normally doesn't show a local `master` branch:
```
$ git branch
  eslint
* sealsystems
```

**Comment by goloroden** [comment]
Hi @StefanScherer 😊 

First of all, thanks for bringing this up! To be honest, we didn't have in mind when we designed roboter, that someone could use a different main branch but `master`, but your scenario seems to be legit 😉 

Right now, unfortunately we do *not* have a solution for this. As you may know, we are currently in the process of rewriting roboter from scratch. So the question might be how to deal with this issue in the future.

I think that it is important to have these checks (pending, …), to avoid releasing something accidentally that is outdated. Of course, the simplest approach would be to add a configuration option to the `roboter.js` file to configure the branch name – but this won't work, as we strive for a zero-configuration approach, where the file `roboter.js` does not exist any longer.

So, the question might be whether it is possible to detect the main branch using `git` itself`? Is there a command for this?

**Comment by StefanScherer** [comment]
Thanks @goloroden 
I'll try to find out how we can find the default branch name. I also prefer a zero config solution 

A cloned repo with `sealsystems` branch as default on GitHub:

```
$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/sealsystems
  origin/sealsystems
```

A cloned repo with `master` branch as default on GitHub:

```
$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/master
  origin/master
```

**Comment by goloroden** [comment]
Is this still true after you have switched to another branch, e.g. a feature branch, manually?

**Comment by StefanScherer** [comment]
Yes. Sorry I automatically removed my bash prompt today morning 😬 

Here is a complete output:

```
~/code/sealsystems/node-ipp on sealsystems
$ git branch
  add-infra-comments
  eslint
  master
* sealsystems
~/code/sealsystems/node-ipp on sealsystems
$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/sealsystems
  origin/sealsystems
~/code/sealsystems/node-ipp on sealsystems
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/code/sealsystems/node-ipp on master
$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/sealsystems
  origin/sealsystems
~/code/sealsystems/node-ipp on master
$ git checkout add-infra-comments
Switched to branch 'add-infra-comments'
Your branch is up-to-date with 'origin/add-infra-comments'.
~/code/sealsystems/node-ipp on add-infra-comments
$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/sealsystems
  origin/sealsystems
~/code/sealsystems/node-ipp on add-infra-comments
```

In every local branch I get `origin/sealsystems`.

**Comment by goloroden** [comment]
I tried to run this in one of my locally cloned repositories, but I got an error:

```shell
$ git branch -r --points-at refs/remotes/origin/HEAD
error: malformed object name 'refs/remotes/origin/HEAD'
```

Any idea of what might be wrong?

**Comment by StefanScherer** [comment]
Hm, I'm using 

```
$ git --version
git version 2.10.0
```

Maybe a version conflict?

**Comment by goloroden** [comment]
Mine is newer:

```shell
$ git --version
git version 2.14.3
```

Hmmmm… 🤔

**Comment by StefanScherer** [comment]
OK, I'll update ;-)

Well, we found the command here: https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch

The branch name is also in a file. Maybe we find a more compatible command.

```
$ cat .git/refs/remotes/origin/HEAD 
ref: refs/remotes/origin/sealsystems
```

**Comment by StefanScherer** [comment]
Upgraded to Git 2.16.1, it still works here.

```
$ git --version
git version 2.16.1

$ cat .git/refs/remotes/origin/HEAD 
ref: refs/remotes/origin/sealsystems

$ git branch -r --points-at refs/remotes/origin/HEAD
  origin/HEAD -> origin/sealsystems
  origin/sealsystems
```

**Comment by goloroden** [comment]
We won't fix this for the current roboter branch.

We are currently preparing a completely rewritten version, which will be available soon. We then have to see whether and, if, how to fix it there.
