### ISSUE TITLE
Installing module using npm failed 

### ISSUE THREAD

**Issue by veera83372** [thenativeweb/roboter#55]
I tried to install roboter using npm 
```bash 
npm install roboter
```
but I got the following error
![screen shot 2018-03-16 at 11 47 35 am](https://user-images.githubusercontent.com/17177346/37506508-2cd11cfe-2910-11e8-8039-cbb5a6ab41e4.png)

**Comment by goloroden** [comment]
TBH I rather think that this is caused by some corruption in your npm cache or something similar, as it works perfectly on various machines.

Can ou please try to entirely delete the node_modules directory and the package-lock.json file, and reinstall everything from scratch?

**Comment by veera83372** [comment]
@goloroden Can you please have a look at it.
[![asciicast](https://asciinema.org/a/170114.png)](https://asciinema.org/a/170114)

**Comment by goloroden** [comment]
Hmmm, that's really strange 🤔

**Comment by veera83372** [comment]
What is preferable node version for this package ??

**Comment by goloroden** [comment]
Latest LTS, so 8.x

**Comment by mattwagl** [comment]
Looks similar [to this problem](https://github.com/npm/npm/issues/18036). Can yout try to run…

```
$ npm cache clean --force
```

**Comment by veera83372** [comment]
@mattwagl
Thanks it is resolved by running that cmd
