### ISSUE TITLE
Support pretest posttest for test-units

### ISSUE THREAD

**Issue by StefanScherer** [thenativeweb/roboter#57]
For tests requiring a MongoDB I found a very convenient way in https://github.com/sealsystems/node-mongo/pull/5/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16 to add `pretest` and `posttest` and using the `mongodb-runner`. This keeps my tests clean, I don't have to add code in the tests itself.

A `npm run test` works fine as it calls `pretest`, `test` and `posttest` automatically.

How can I achieve that with Roboter in a `roboter.js` file?

**Comment by goloroden** [comment]
Hi @StefanScherer 😊 

roboter can do this, but it is not using the entries of the `package.json` file.

Have a look at [the integration test](https://github.com/thenativeweb/roboter#the-test-integration-task) documentation, and watch out for the `pre.js` and `post.js` files. Although not documented, this works for unit tests in the same way.

This is also the way of how things will work with the upcoming release of roboter that was rewritten from scratch.
