### ISSUE TITLE
Roboter doesn't parse `.eslintrc`

### ISSUE THREAD

**Issue by fhemberger** [thenativeweb/roboter#73]
Besides `.eslintrc.json`, `.eslintrc` is a valid config file for ESLint as well.
Roboter should check for both: https://github.com/thenativeweb/roboter/blob/master/lib/automation/quality/analyseCode.js#L27

**Comment by goloroden** [comment]
Using `.eslintrc` without a file extension is deprecated (see https://eslint.org/docs/user-guide/configuring#configuration-file-formats for details), hence we don't support it (especially since the fix is pretty trivial, as you simply need to rename your file).

**Comment by fhemberger** [comment]
Ah okay, didn't know it was deprecated. Updating all the modules … yay! 😒

**Comment by goloroden** [comment]
Maybe [forany](https://www.npmjs.com/package/forany) can be helpful here 😉

**Comment by fhemberger** [comment]
Thanks, I'm more the `find . -name ".eslintrc" -not -path "*/node_modules/*" -exec mv {} {}.json \;` type. 😁

**Comment by goloroden** [comment]
This, of course, works as well 👍
