### ISSUE TITLE
Check usage of @types dependencies.

### ISSUE THREAD

**Issue by yeldiRium** [thenativeweb/roboter#94]
Currently (dev-)dependencies to packages providing TypeScript type declarations are always marked as unused. They should actually be checked and only reported as unused, if their declarations are not used anywhere.

In the package we use for this ([depcheck](https://github.com/depcheck/depcheck/)) there is an [open issue](https://github.com/depcheck/depcheck/issues/163) for this.

**Comment by goloroden** [comment]
Fixed in 3ecbd815cb18e2931826573e7d8576de857660be
